### ISSUE TITLE
[pri-fidoiot]  Failure in SVI file transfer when a owner container reaches memory limit 

### ISSUE THREAD

**Issue by Sai-Anudeep47** [secure-device-onboard/pri-fidoiot#524] opened 2022-07-21 09:32 UTC
When a running owner container reaches memory limit set in the respective docker-compose.yml file, an error is observed on the client side during SVI transfer and the owner container restarts.

**Comment by DukeDavis12** [comment] 2022-07-26 11:41
In the case of transferring a large payload file via ServiceInfo, there is a possibility that the running container might hit the memory limit set in the respective docker-compose.yml file.
This can be confirmed using the `docker stats` command that shows live resource statistics for running containers.

During SVI Transfer, observe the column `MEM USAGE / LIMIT` for the respective containers when SVI transmission is in progress.
If the failure is observed when MEM USAGE reaches the LIMIT, it is due to the memory limit we have allocated for the container.
To resolve this, edit fields `mem_limit` and `mem_reservation` in the respective docker-compose.yml according to the needs and restart the container.

**Closed by DukeDavis12** 2022-07-26 11:41 UTC
